all:
	python manage.py makemigrations
	python manage.py migrate
	python manage.py runserver

test:
	python manage.py test

db:
	python manage.py makemigrations
	python manage.py migrate

server: 
	python manage.py runserver


